export enum AwsResourceTypes {
	vpc = "vpc",
	cluster = "cluster",
	loadBalancer = "lb",
	httpsCertificate = "https-certificate",
	route53Zone = "route53-zone",
	dnsRecord = "dns-record",
	dnsARecord = "dns-a-record",
	securityGroup = "security-group",
	lbListener = "lb-listener",
	lbListenerRule = "lb-listener-rule",
	fargateService = "fargate-service",
	taskDefinition = "task-definition",
	targetGroup = "tg",
	serviceContainer = "service-container",
	user = "user",
	userLoginProfile = "user-login-profile",
	accessKey = "access-key",
	userGroupMembership = "user-group-membership",
	userGroup = "user-group",
	policyAttachment = "policy-attachment",
	permissionsPolicy = "permissions-policy",
	imageRepository = "image-repository",
	image = "image",
}
