export enum ResourceTypes {
	vpc = "vpc",
	cluster = "cluster",
	loadBalancer = "lb",
	securityGroup = "security-group",
	lbListener = "lb-listener",
	fargateService = "fargate-service",
	user = "user",
	userGroup = "user-group",
	policyAttachment = "policy-attachment",
	permissionsPolicy = "permissions-policy",
	app = "app",
	imageRepository = "image-repository",
	service = "service",
}
