export enum ResourceTypes {
	vpc = "vpc",
	cluster = "cluster",
	loadBalancer = "lb",
	httpsCertificate = "https-certificate",
	route53Zone = "route53-zone",
	dnsRecord = "dns-record",
	securityGroup = "security-group",
	lbListener = "lb-listener",
	lbListenerRule = "lb-listener-rule",
	fargateService = "fargate-service",
	taskDefinition = "task-definition",
	targetGroup = "target-group",
	serviceContainer = "service-container",
	user = "user",
	userGroup = "user-group",
	policyAttachment = "policy-attachment",
	permissionsPolicy = "permissions-policy",
	app = "app",
	imageRepository = "image-repository",
	service = "service",
}
