LAMBDA_FUNCTION_NAME=$1
LAMBDA_REGION=$2
DATADOG_API_SECRET_ARN=$3


export DATADOG_SITE="datadoghq.eu"

export DATADOG_API_KEY_SECRET_ARN=DATADOG_API_SECRET_ARN

datadog-ci lambda instrument -f $LAMBDA_FUNCTION_NAME -r $LAMBDA_REGION -v 115 -e 65